#!/bin/tcsh
### Job Name
#PBS -N NM 
### Project code
#PBS -A UCUD0003 
#PBS -l walltime=2:00:00
#PBS -q regular
### Merge output and error files
#PBS -j oe
### Select 2 nodes with 36 CPUs each for a total of 72 MPI processes
#PBS -l select=ND:ncpus=36:mpiprocs=36
### Send email on abort, begin and end
#PBS -m abe
### Specify mail recipient
#PBS -M jan.mandel@gmail.com 

module load ncarenv intel ncarcompilers mpt netcdf
pwd
git log | head -1
rm rsl.out.* rsl.error.* wrfout_* wrfinput_*

### Run the executable
mpiexec_mpt -np 1 omplace -vv ./ideal.exe
mv rsl.error.0000 ideal.log
mv rsl.out.0000 ideal.out
/usr/bin/time -v mpiexec_mpt -np NP omplace -vv ./wrf.exe
